name: apptest
description: "Focus TimeCapsule"
publish_to: 'none'
version: 0.1.0

google_fonts: ^6.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_inner_shadow: ^0.0.1
  animated_toggle: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/
